config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pins
  devise_for :users
  root "pins#index"
  get "about" => "pages#about"
  get "stripepayments" => "pages#stripepayments"
  resources :charges 

  resources :purchases, only: [:show]

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, styles: { :small => "150x150>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/models/purchase.rb
class PurchaseMailer < ActiveRecord::Base
	
	after_create :email_purchaser

	def to_param
 	uuid
	end

	private

	def email_purchaser
   PurchaseMailer.purchase_receipt(self).deliver
	end 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

def create
  

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => params[:amount],
    :description => 'Growth Hacking Crash Course',
    :currency    => 'usd'
  )

  purchase = Purchase.create(email: params[:stripeEmail], card: params[:stripeToken], 
    amount: params[:amount], description: charge.description, currency: charge.currency,
    customer_id: customer.id, product_id: 1, uuid: SecureRandom.uuid)

redirect_to purchase

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
   def about
  end
  def stripepayments
  end	
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show] 

  def index
   @pins = Pin.all.order("created_at DESC")
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render :new
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find_by(id: params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def show
    @purchase = Purchase.find_by_uuid(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/charges/create.html.erb
Purchase Successful!

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <<%= link_to "Pinteresting", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li> 
      <li><%= link_to "Stripe", stripepayments_path %></li>
      <% if user_signed_in? %>
       <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
          </li>
      <li><%= link_to "Account Settings", edit_user_registration_path %></li>
      <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li> 
      <% else %>
      <li><%= link_to "Sign In", new_user_session_path %></li> 
      <% end %> 
    </ul>
    </div>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
     <div class="container">
          <div id="content" class="container">
    <header id="content-header">
        <div id="price-container">
          <span class="glyphicon glyphicon-tag"></span><span class="price">$4.99</span>
        </div>
        <%= image_tag('header-image.jpg', id: 'content-header-img', alt: 'Learn Growth Hacking') %>
    </header>

          <% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, class: "alert-info") %>
          <% end %>
          <%= yield %>
          </div>
     </div>

</body>
</html>

app/views/layouts/purchase_mailer.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>One Month Stripe Payments</title>
</head>
<body>

	<%= yield %>

	<p> Thanks for buying from us!</p>
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
  <h1>Welcome to my app!</h1>
  <p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>

</div>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p> Jeremy Wade </p>

app/views/pages/main.html.erb
main.html.erb

app/views/pages/stripepayments.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, user-scalable=no">
  <title>OneMonthGrowthHacking</title>
    <link rel="stylesheet" href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300,800' >
    <link rel="stylesheet" href="css/main.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

    <section id="content-details" class="row clearfix">
        <article id="details-article" class="col-sm-8">
            <h1 id="article-title">Growth Hacking <span class="font-weight-light">Crash Course</span></h1>
            <h3><small>By <a href="#" data-toggle="modal" data-target="#author-modal">Mattan Griffel</a></small></h3>

            <p>A growth hacker is a rare combination: someone with the right marketing and technical skills who can come up with clever marketing hacks and also track their results.</p>

            <p>In this talk, Mattan Griffel introduces you to the concept of Growth Hacking and shares his favorite tips for getting started as a growth hacker.</p>
            <p><strong>What You'll Learn</strong></p>
            <ul class="no-indent">
                <li>What is a growth hacker?</li>
                <li>The 5 stages of the user lifecycle</li>
                <li>How to apply the Lean Marketing Framework</li>
                <li>Resources and tools you'll need to know</li>
            </ul>
        </article>
        <aside id="details-aside" class="col-sm-4">
            <!-- <a id="btn-buy" href="receipt.html" class="btn btn-success btn-lg btn-block"><span class="glyphicon glyphicon-ok"></span>I want this!</a> -->

  <%= form_tag charges_path, id: 'chargeForm' do %>
    <script src="https://checkout.stripe.com/checkout.js"></script>
    <%= hidden_field_tag 'stripeToken' %>
    <%= hidden_field_tag 'stripeEmail' %> 
    <%= hidden_field_tag 'amount', 499 %>
    <button id="btn-buy" type="button" class="btn btn-success btn-lg btn-block"><span class="glyphicon glyphicon-ok"></span>I want this!</button>
    <script>
    var handler = StripeCheckout.configure({
      key: '<%= Rails.configuration.stripe[:publishable_key] %>',
      token: function(token, arg) {
        document.getElementById("stripeToken").value = token.id;
        document.getElementById("stripeEmail").value = token.email;
        document.getElementById("chargeForm").submit();
      }
    });
     document.getElementById('btn-buy').addEventListener('click', function(e) {
      handler.open({
        name: 'One Month',
        description: 'Growth Hacking Crash Course ($499)',
    });
    e.preventDefault();
   })
  </script>
<% end %>
            <ul id="details-infobox" class="list-group">
              <li class="list-group-item active clearfix">DETAILS</li>
              <li class="list-group-item">You'll get one video</li>
              <li class="list-group-item clearfix">
                <span class="pull-left content-qualifier">Length</span>
                <span class="pull-right">30 minutes</span>
              </li>
            </ul>
        </aside>
    </section>
</div>
<footer id="site-footer">
Made by <a href="http://onemonth.com" target="_blank"></a>
<%= image_tag('one-month-logo.svg', id: 'one-month-footer-logo', alt: 'One Month') %>
</footer>

<!-- Modal -->
<div class="modal fade" id="author-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title"><span class="glyphicon glyphicon-user"></span>About the Teacher</h4>
      </div>
      <div class="modal-body clearfix">
            <div id="modal-left" class="pull-left">
                <p><strong>Mattan Griffel</strong></p>
                <p>Hey, I'm Mattan Griffel, co-founder of the Y Combinator backed <a href="http://www.onemonth.com" target="_blank">One Month</a> where I teach the best selling One Month Rails and One Month Growth Hacking.</p>
                <p>Why take my class? In the past I've advised companies like Pepsico, Bloomberg, GM, NYSE, and JPMorgan on growth hacking best practices. I've also spoken at New York University, Cooper Union and First Round Capital. My goal is to help you and other entrepreneurs rapidly grow your business. 
                </p>
                <p>Follow me on Twitter <a href="https://twitter.com/mattangriffel" target="_blank">@mattangriffel</a></p>
            </div>
            <div id="modal-right" class="pull-right">
                <%= image_tag('teacher-image.jpg', alt: 'Mattan Griffel') %>
            </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>

app/views/pins/_form.html.erb
<%= form_for (@pin), html: { multipart: true }  do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>

    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %><br/>
        <strong><%= pin.user.email if pin.user %></strong>
        <% if pin.user == current_user %>
          <div class="actions">
               <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <p><%= @pin.description %></p>
        <p><strong><%= @pin.user.email if @pin.user %></strong></p>

        <% if @pin.user == current_user %>
         <%= link_to edit_pin_path(@pin) do %>
        <span class="glyphicon glyphicon-edit"></span>
        Edit
      <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/purchases/show.html.erb
<section id="content-receipt" class="clearfix">
 <div id="receipt-container">
  <div class="dotmatrix left"></div>
   <div id="receipt-content">
   <h4 id="receipt-title">Thank You!</h4>
   <p><strong>RECEIPT</strong></p>
     <div id="receipt-details" class="row clearfix">
  <div class="col-sm-8 receipt-left">
<p><strong class="font-weight-heavy">Growth Hacking</strong><br/> <span class="font-weight-light">Crash Course</span></p>
    </div>
<div class="col-sm-4">
$499
 </div>
</div>
<a href="https://s3.amazonaws.com/one_month_stripe_payment/Peter+Bell+Resume.pdf"><button type="button" class="btn btn-success btn-xs">DOWNLOAD</button></a>
<footer id="receipt-footer">
<small>Your purchase is complete. We hope you enjoy it!</small>
</footer>
 </div>
<div class="dotmatrix right"></div>
 </div>
<div id="receipt-shadow"></div>
</section>